version: '3.6'
services:

  crawler:
    restart: on-failure
    build:
      context: .
      dockerfile: crawler/Dockerfile
    env_file:
      - crawler/src/config/.env
    depends_on:
      - redis
    ports:
      - 8081:8081
    command: >
      /bin/sh -c "
        npm install -g nodemon && nodemon -e py --watch src --exec 'python3 -u src/app.py';
      "
    volumes:
      - ./crawler/src:/service/app/src
    hostname: crawler

  redis:
    restart: always
    image: redis:5.0-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    hostname: redis

volumes:
    db_data:
